"use client";
import {useState} from 'react';
import MotionPhone, {ExerciseVideo} from './MotionPhone';
const gym='https://images.unsplash.com/photo-1548932813-88dcf75599c6?auto=format&fit=crop&w=1200&q=85';
const food='https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85';
type Screen='workout'|'nutrition'|'progress'|'coach';
export function ProductPhone({screen='workout',compact=false}:{screen?:Screen;compact?:boolean}){
 const [water,setWater]=useState(3);const [meal,setMeal]=useState('Balanced');const [checked,setChecked]=useState(false);
 if(screen==='workout') return <MotionPhone/>;
 return <div className={'product-phone '+(compact?'compact':'')}><div className="device-island"/><div className="device-status"><b>9:41</b><span>▂▄▆ ▰</span></div><div className="device-brand"><b>R</b>epCount <small>DEMO</small></div>
 
 {screen==='nutrition'&&<><div className="screen-greeting"><span>NOURISH YOUR ROUTINE</span><h3>Your day.<br/>On a plate.</h3></div><div className="device-pills">{['Balanced','Vegetarian'].map(m=><button key={m} className={meal===m?'chosen':''} onClick={()=>setMeal(m)}>{m}</button>)}</div><div className="device-food"><img src={food} alt="Colourful vegetable bowl illustrating meal planning"/><span>MEAL PLAN PREVIEW</span></div><h4 className="device-section-title">{meal==='Vegetarian'?'Colourful vegetable bowl':'A balanced lunch bowl'}</h4><p className="device-description">Meals, preferences and your daily routine, together.</p><div className="device-meals"><div><span>08:00</span><b>Breakfast</b><small>Oats, fruit & yoghurt</small></div><div><span>13:00</span><b>Lunch</b><small>{meal==='Vegetarian'?'Vegetables, lentils & rice':'Vegetables, rice & protein'}</small></div><div><span>19:30</span><b>Dinner</b><small>Your agreed meal plan</small></div></div><p className="device-disclaimer">Illustrative meals only. Nutrition scope and professional review are to be confirmed.</p></>}
 {screen==='progress'&&<><div className="screen-greeting"><span>EVERY SMALL WIN COUNTS</span><h3>Look how far<br/>you’ve come.</h3></div><div className="device-progress-ring" style={{background:checked?"conic-gradient(#e62940 100%,#e6e9f0 0)":"conic-gradient(#e62940 75%,#e6e9f0 0)"}}><div><b>{checked?'4':'3'}<small>/4</small></b><span>weekly workouts</span></div></div><div className="device-stats"><div><b>{checked?'100%':'75%'}</b><span>Plan completion</span></div><div><b>Week 1</b><span>Your programme</span></div></div><div className="device-chart" aria-label="Illustrative workout minutes"><i style={{height:'35%'}}/><i style={{height:'60%'}}/><i style={{height:'48%'}}/><i style={{height:'80%'}}/><i style={{height:'65%'}}/><i style={{height:'92%'}}/></div><h4 className="device-section-title">Today’s habits</h4><button className="device-habit" onClick={()=>setWater(Math.min(8,water+1))}><span>Water logged</span><b>{water}/8 glasses <i>+</i></b></button><button className="device-habit" aria-pressed={checked} onClick={()=>setChecked(!checked)}><span>Sample workout</span><b>{checked?'Completed ✓':'Mark complete ○'}</b></button><p className="device-disclaimer">Sample activity, not a health score. Water goal is illustrative.</p></>}
 {screen==='coach'&&<><div className="screen-greeting"><span>PERSONAL. HUMAN. CONNECTED.</span><h3>Meet your<br/>support team.</h3></div><ExerciseVideo variant="review"/><div className="review-person"><span>AK</span><div><b>Akif · trainer coordination</b><small>Proposed team · sample review below</small></div></div><div className="device-chat"><small>WHAT COACHING CAN LOOK LIKE</small><p>Let’s work around your schedule and build a routine you can keep.</p></div><div className="device-chat reply"><p>I’d like to train at home three days a week.</p></div><div className="device-appointment"><span>◎</span><div><b>Weekly trainer follow-up</b><small>Review · Adjust · Keep moving</small></div></div><p className="device-disclaimer">Illustrative conversation. No message or appointment is sent.</p></>}
 <div className="device-bottom"><span>◫<small>Today</small></span><span>◷<small>Plan</small></span><span>↗<small>Progress</small></span><span>◎<small>Coach</small></span></div><div className="device-home"/></div>
}
export function ProductHero({onStart,onEnter}:{onStart:()=>void;onEnter:()=>void}){const [screen,setScreen]=useState<Screen>('workout');return <><section className="showcase-hero"><img className="showcase-athlete" src={gym} alt="Lean muscular athlete training with a dumbbell"/><div className="showcase-shade"/><div className="showcase-copy"><p className="showcase-eyebrow">YOUR FITNESS. ALL TOGETHER.</p><h1>A trainer.<br/>A plan.<br/><em>A stronger you.</em></h1><p>Personal coaching, workouts, diet planning and progress tracking. One place to build your routine.</p><button className="lp-primary lp-big" onClick={onStart}>Build your starting point ↗</button><button className="showcase-demo-link" onClick={onEnter}>Explore the member demo →</button><small>Interactive concept · Diet planning shown as a preview</small></div><div className="showcase-device"><ProductPhone key={screen} screen={screen}/><div className="showcase-tabs" role="group" aria-label="Choose app screen">{(['workout','nutrition','progress'] as Screen[]).map(s=><button key={s} className={screen===s?'active':''} aria-pressed={screen===s} onClick={()=>setScreen(s)}>{s==='workout'?'Workouts':s==='nutrition'?'Diet plan':'Trackers'}</button>)}</div></div><span className="showcase-photo-credit">Rohit Reddy / Unsplash · Illustrative photography</span></section><div className="product-feature-strip"><a href="#trainers">Personal trainers ↗</a><a href="#workouts">Workout plans ↗</a><a href="#diet">Diet planning ↗</a><a href="#trackers">Progress & habits ↗</a></div></>}
export default function FeatureShowcase({onEnter}:{onEnter:()=>void}){return <section className="product-showcase" id="approach"><div className="product-showcase-heading"><p className="showcase-eyebrow">SEE WHAT YOUR ROUTINE COULD LOOK LIKE</p><h2>Your goals. Your people.<br/><em>Your everyday essentials.</em></h2><p>A closer look at the RepCount experience. Try the controls inside the phone previews.</p></div><div className="product-grid"><article className="product-panel workout-panel" id="workouts"><div className="panel-copy"><span>01 / TRAIN WITH A PLAN</span><h3>See the move. Find your rhythm.</h3><p>Real exercise video, a working timeline and sample set tracking. Switch to statistics to explore your training week.</p></div><div className="panel-phone"><ProductPhone screen="workout"/></div><div className="feature-float"><span>✓</span><div><b>Built around your routine</b><small>Home or gym. Beginner or returning.</small></div></div></article><article className="product-panel coach-panel" id="trainers"><img className="panel-background" src={gym} alt="Strength training in a gym"/><div className="panel-tint"/><div className="panel-copy"><span>02 / PERSONALISED COACHING</span><h3>A real person in your corner.</h3><p>See how a video review could look alongside personal trainer guidance and weekly follow-ups.</p></div><div className="panel-phone"><ProductPhone screen="coach"/></div></article><article className="product-panel food-panel" id="diet"><div className="panel-copy"><span>03 / DIET PLAN PREVIEW</span><h3>Make room for better meals.</h3><p>Explore meal schedules and food preferences alongside your training. Nutrition service details are being finalised.</p></div><div className="panel-phone"><ProductPhone screen="nutrition"/></div><div className="food-decoration"><img src={food} alt="Fresh vegetables and a colourful meal bowl"/></div></article><article className="product-panel tracker-panel" id="trackers"><div className="panel-copy"><span>04 / TRACK YOUR CONSISTENCY</span><h3>Small wins. Visible progress.</h3><p>Log workouts, follow weekly completion and track everyday habits. Progress you can understand.</p></div><div className="panel-phone"><ProductPhone screen="progress"/></div><div className="feature-float progress-float"><span>↗</span><div><b>Your effort adds up.</b><small>One session. One check-in. One step.</small></div></div></article></div><div className="product-showcase-bottom"><p>Sample screens and statistics. Videos: <a href="https://mixkit.co/free-stock-video/a-muscular-shirtless-young-man-doing-squats-and-lifting-dumbbells-52082/" target="_blank" rel="noreferrer">Mixkit squat</a> · <a href="https://mixkit.co/free-stock-video/man-lifting-weights-in-the-gym-100544/" target="_blank" rel="noreferrer">Mixkit bench press</a>. No live health measurements.</p><button className="lp-primary" onClick={onEnter}>Step inside the member demo ↗</button></div></section>}



