"use client";
import {useState,useRef,useEffect} from 'react';
import FeatureShowcase, {ProductHero} from './FeatureShowcase';
const athlete='https://images.unsplash.com/photo-1548932813-88dcf75599c6?auto=format&fit=crop&w=1800&q=85';
export default function Landing({onEnter}:{onEnter:()=>void}){
 const [menu,setMenu]=useState(false);
 const [quiz,setQuiz]=useState(false);
 const [step,setStep]=useState(0);
 const [goal,setGoal]=useState('Build strength');
 const [place,setPlace]=useState('At home');
 const [days,setDays]=useState('3 days');
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=ref.current;if(quiz)el?.showModal();return()=>el?.close();},[quiz]);
 function start(){setStep(0);setQuiz(true);}
 const brand=<span className="lp-logo"><b>R</b>epCount</span>;
 return <div className="landing"><a href="#lp-main" className="skip">Skip to content</a><div className="lp-announcement">A PERSONAL APPROACH TO GETTING STRONGER <span>INDIA · ONLINE COACHING</span></div>
 <header className="lp-header"><a href="#" aria-label="RepCount home">{brand}</a><nav aria-label="Main navigation" className={menu?'lp-links expanded':'lp-links'}><a href="#approach" onClick={()=>setMenu(false)}>Features</a><a href="#how" onClick={()=>setMenu(false)}>How it works</a><a href="#programme" onClick={()=>setMenu(false)}>The programme</a><a href="#questions" onClick={()=>setMenu(false)}>FAQs</a></nav><div className="lp-nav-actions"><button className="lp-login" onClick={onEnter}>Member demo <span>↗</span></button><button className="lp-primary" onClick={start}>Find your starting point <span>→</span></button><button className="lp-menu" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'×':'☰'}</button></div></header>
 <main id="lp-main" className="lp-main"><ProductHero onStart={start} onEnter={onEnter}/><FeatureShowcase onEnter={onEnter}/><section className="lp-how" id="how"><div className="lp-section"><div className="lp-section-head"><div><p className="lp-kicker">A SIMPLE START. A STRONGER ROUTINE.</p><h2>Your next chapter,<br/><em>in three steps.</em></h2></div><button className="lp-secondary" onClick={start}>Explore your starting point ↗</button></div><div className="lp-steps">{[['01','Tell us about you.','Start with your goals, preferred training setting and routine. Your first conversation helps put those choices in context.'],['02','Meet your support team.','Psychologist onboarding comes first. Then your trainer builds a plan around the practical guidance you agree to share.'],['03','Move. Check in. Keep going.','Follow your plan, track completed sessions and review your week with your trainer. Adjustments are part of the process.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="lp-team-section"><div className="lp-section"><div className="lp-section-head"><div><p className="lp-kicker">THE PEOPLE BEHIND YOUR PLAN</p><h2>Human support.<br/><em>From the very beginning.</em></h2></div><p>Our proposed pilot team brings training coordination and psychologist onboarding into one considered journey.</p></div><div className="lp-team-grid"><article><span className="lp-person-monogram">AK</span><div><p className="lp-kicker">TRAINER COORDINATION</p><h3>Akif</h3><p>Your point of contact for trainer coordination and a consistent weekly follow-up routine.</p></div><span className="lp-team-arrow">↗</span></article><article><span className="lp-person-monogram">TH</span><div><p className="lp-kicker">PSYCHOLOGIST ONBOARDING</p><h3>Thasleema</h3><p>An initial conversation to understand your needs and agree the guidance your trainer receives.</p></div><span className="lp-team-arrow">↗</span></article></div><p className="lp-team-note">Proposed pilot team. Availability and appointments are to be confirmed before enrolment.</p></div></section>
 <section className="lp-section lp-pricing" id="programme"><div><p className="lp-kicker">THE FOUNDING PILOT</p><h2>30 days.<br/>A stronger<br/><em>starting point.</em></h2><p>A small, online pilot for 10 adults in India. Personal attention, a manageable plan and a weekly conversation to keep you moving.</p><span className="lp-date">PLANNED SERVICE START · 15 OCTOBER 2026</span></div><div className="lp-price-card"><div className="lp-price-top"><span>YOUR 30-DAY PROGRAMME</span><span>FOUNDING COHORT</span></div><div className="lp-price"><sup>AED</sup>250<span>/ 30 days</span></div><p>Personal support from the first conversation.</p><ul><li>Psychologist onboarding session</li><li>A personalised trainer-led workout plan</li><li>Weekly trainer follow-ups</li><li>A space to follow your plan and progress</li></ul><button className="lp-primary" onClick={start}>Explore the pilot <span>↗</span></button><p className="lp-payment-note">Manual payment, verified by the team. India collection currency and payment method will be confirmed before enrolment.</p></div></section>
 <section className="lp-section lp-faq" id="questions"><div><p className="lp-kicker">LET’S CLEAR A FEW THINGS UP</p><h2>Good questions.<br/><em>Straight answers.</em></h2></div><div>{[['Who is the pilot for?','The first pilot is for adults aged 18 and over in India, with online coaching and an initial cohort of 10 clients.'],['Do I need a gym membership?','The proposed programme can be planned around training at home or at a gym. Your trainer will discuss your available space and equipment before finalising your plan.'],['How does psychologist onboarding work?','The programme includes an initial session with the psychologist. You agree what practical guidance may be shared with the trainer. Private counselling notes should stay separate from general training records.'],['Is nutrition coaching included?','Nutrition support and professional responsibility are still being defined. A nutritionist and personalised meal plans are not confirmed inclusions.'],['How do payments work?','Payment is manual, through an external method to be agreed. The team verifies receipt before activating programme access. This demo does not collect money.'],['Can I sign up or log in today?','This is an interactive design demo. The goal quiz and member area use sample information only. Real enrolment, secure accounts and bookings will be enabled when the service is ready.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="lp-final"><p className="lp-kicker">YOUR NEXT CHAPTER STARTS WITH ONE STEP</p><h2>Make every<br/><em>rep count.</em></h2><button className="lp-primary lp-big" onClick={start}>Find your starting point <span>↗</span></button><p>Your goals. A human connection. A way forward.</p></section></main><footer className="lp-footer"><div>{brand}<p>Personal training. Thoughtful support.</p></div><div><a href="#approach">Features</a><a href="#programme">The programme</a><button onClick={onEnter}>Member demo ↗</button></div><div className="lp-footer-bottom"><span>© 2026 RepCount · India pilot</span><span>Design demo · No live enrolment or payments</span></div></footer>
 <dialog className="lp-quiz" ref={ref} onCancel={()=>setQuiz(false)} aria-labelledby="quiz-title"><div className="dialog-inner"><button className="close" aria-label="Close quiz" onClick={()=>setQuiz(false)}>×</button><p className="lp-kicker">YOUR STARTING POINT · DEMO</p><div className="lp-quiz-progress"><span style={{width:`${(step+1)*25}%`}}/></div><h2 id="quiz-title">{['What would you like to work on?','Where will you feel at home?','What feels manageable?','Your starting point, mapped out.'][step]}</h2>{step<3?<><p>{['Choose the goal that matters most to you.','A good plan starts with the space you have.','This is a preference, not a prescribed workout schedule.'][step]}</p><div className="lp-options">{(step===0?['Build strength','Build a consistent routine','Feel more confident exercising']:step===1?['At home','At a gym','A mix of both']:['2 days','3 days','4 days']).map(v=><button key={v} className={(step===0?goal:step===1?place:days)===v?'chosen':''} aria-pressed={(step===0?goal:step===1?place:days)===v} onClick={()=>step===0?setGoal(v):step===1?setPlace(v):setDays(v)}>{v}<span>{(step===0?goal:step===1?place:days)===v?'✓':'○'}</span></button>)}</div><div className="lp-quiz-buttons">{step>0&&<button className="lp-back" onClick={()=>setStep(step-1)}>← Back</button>}<button className="lp-primary" onClick={()=>setStep(step+1)}>Continue →</button></div></>:<><div className="lp-quiz-result"><p><span>YOUR GOAL</span><b>{goal}</b></p><p><span>YOUR SETTING</span><b>{place}</b></p><p><span>YOUR PREFERENCE</span><b>{days} per week</b></p></div><p>Your next real step would be an onboarding conversation, followed by a trainer-approved plan. This preview has not submitted an application or matched you to a coach.</p><button className="lp-primary" onClick={()=>{setQuiz(false);onEnter();}}>Explore the sample member experience ↗</button><button className="lp-back" onClick={()=>setStep(0)}>Start again</button></>}<small>Demo only · No personal or health information collected.</small></div></dialog></div>;
}


