"use client";
import {useState,useRef,useEffect} from 'react';
const athlete='https://images.unsplash.com/photo-1548932813-88dcf75599c6?auto=format&fit=crop&w=1800&q=85';
export default function Landing({onEnter}:{onEnter:()=>void}){
 const [menu,setMenu]=useState(false);
 const [quiz,setQuiz]=useState(false);
 const [step,setStep]=useState(0);
 const [goal,setGoal]=useState('Build strength');
 const [place,setPlace]=useState('At home');
 const [days,setDays]=useState('3 days');
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=ref.current;if(quiz)el?.showModal();return()=>el?.close();},[quiz]);
 function start(){setStep(0);setQuiz(true);}
 const brand=<span className="lp-logo"><b>R</b>epCount<span>®</span></span>;
 return <div className="landing"><a href="#lp-main" className="skip">Skip to content</a><div className="lp-announcement">A PERSONAL APPROACH TO GETTING STRONGER <span>INDIA · ONLINE COACHING</span></div>
 <header className="lp-header"><a href="#" aria-label="RepCount home">{brand}</a><nav aria-label="Main navigation" className={menu?'lp-links expanded':'lp-links'}><a href="#approach" onClick={()=>setMenu(false)}>Our approach</a><a href="#how" onClick={()=>setMenu(false)}>How it works</a><a href="#programme" onClick={()=>setMenu(false)}>The programme</a><a href="#questions" onClick={()=>setMenu(false)}>FAQs</a></nav><div className="lp-nav-actions"><button className="lp-login" onClick={onEnter}>Member demo <span>↗</span></button><button className="lp-primary" onClick={start}>Find your starting point <span>→</span></button><button className="lp-menu" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'×':'☰'}</button></div></header>
 <main id="lp-main" className="lp-main"><section className="lp-hero"><div className="lp-hero-image"><img src={athlete} alt="Lean muscular athlete strength training with a dumbbell" fetchPriority="high"/></div><div className="lp-hero-overlay"/><div className="lp-hero-content"><p className="lp-kicker"><span/> PERSONAL TRAINING. A HUMAN CONNECTION.</p><h1>Built around you.<br/>Stronger<br/><em>with someone.</em></h1><p className="lp-lead">A plan that fits your life. A coach who helps you show up. Make your next chapter your strongest one yet.</p><button className="lp-primary lp-big" onClick={start}>Find your starting point <span>↗</span></button><p className="lp-hero-foot">Your goals. Your pace. Real personal support.</p></div><div className="lp-floating"><span className="lp-floating-icon">↗</span><div><small>THE REPCOUNT APPROACH</small><b>Personal coaching.<br/>Every step of the way.</b></div></div><span className="lp-image-note">Illustrative photography · Rohit Reddy / Unsplash</span><div className="lp-hero-index">01 <span>/ YOUR NEXT CHAPTER</span></div></section>
 <div className="lp-proof"><div><span>01</span><b>A plan made for you</b></div><div><span>02</span><b>Weekly human follow-ups</b></div><div><span>03</span><b>Mindful onboarding</b></div><div><span>04</span><b>Home or gym. Your call.</b></div></div>
 <section className="lp-section lp-intro" id="approach"><div><p className="lp-kicker">FITNESS THAT FITS YOUR LIFE</p><h2>You bring the why.<br/>We help with <em>the how.</em></h2></div><div><p>Starting is a moment. Staying with it takes support. RepCount brings personal training and thoughtful onboarding together, so your routine starts with understanding you.</p><p>Your coach helps turn your goals into practical sessions. Weekly follow-ups make space to celebrate progress and adjust when life changes.</p><a className="lp-text-link" href="#how">See how it comes together <span>↘</span></a></div></section>
 <section className="lp-features lp-section"><article className="lp-feature lp-feature-dark"><span className="lp-feature-number">01 / PERSONAL</span><div className="lp-plan-visual" aria-label="Illustrative weekly plan"><div><span>YOUR WEEK</span><span>↗</span></div><div className="lp-plan-days">{['M','T','W','T','F','S','S'].map((d,i)=><span key={i} className={[0,2,4].includes(i)?'is-training':''}>{d}</span>)}</div><div className="lp-plan-session"><span>↗</span><div><b>Strength, on your schedule.</b><small>Your coach shapes the details.</small></div></div></div><h3>A plan with your name on it.</h3><p>Your goals, your experience and the equipment you have. A clear next step whenever you open your plan.</p></article><article className="lp-feature"><span className="lp-feature-number">02 / CONNECTED</span><div className="lp-message-visual"><span className="lp-initial">RC</span><div><small>THE KIND OF SUPPORT WE BELIEVE IN</small><p>Let’s look at what worked this week, and what we can make easier.</p></div></div><h3>Someone in your corner.</h3><p>Weekly trainer follow-ups bring accountability, encouragement and room to adapt. Progress is a conversation.</p></article><article className="lp-feature lp-feature-warm"><span className="lp-feature-number">03 / THOUGHTFUL</span><div className="lp-mind-visual"><span>YOU</span><i/><i/><i/></div><h3>A person, before a programme.</h3><p>Begin with psychologist onboarding. Agree what useful guidance may be shared with your trainer, while private notes stay separate.</p></article></section>
 <section className="lp-how" id="how"><div className="lp-section"><div className="lp-section-head"><div><p className="lp-kicker">A SIMPLE START. A STRONGER ROUTINE.</p><h2>Your next chapter,<br/><em>in three steps.</em></h2></div><button className="lp-secondary" onClick={start}>Explore your starting point ↗</button></div><div className="lp-steps">{[['01','Tell us about you.','Start with your goals, preferred training setting and routine. Your first conversation helps put those choices in context.'],['02','Meet your support team.','Psychologist onboarding comes first. Then your trainer builds a plan around the practical guidance you agree to share.'],['03','Move. Check in. Keep going.','Follow your plan, track completed sessions and review your week with your trainer. Adjustments are part of the process.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="lp-section lp-app-section"><div><p className="lp-kicker">A LITTLE CLARITY GOES A LONG WAY</p><h2>Less figuring it out.<br/>More <em>showing up.</em></h2><p>Your workout, your progress and your next check-in, together in one simple space. Open it on your phone. Pick up where you left off.</p><ul><li>A clear workout for your day</li><li>Progress that makes sense</li><li>Your next conversation, easy to find</li></ul><button className="lp-primary" onClick={onEnter}>Explore the member demo <span>↗</span></button><small>Interactive preview with sample data. No account needed.</small></div><div className="lp-app-stage"><div className="lp-phone"><div className="lp-phone-top">9:41 <span>● ▰</span></div><div className="lp-phone-brand"><b>R</b>epCount</div><p>YOUR SPACE TO MOVE FORWARD</p><h3>Good morning,<br/>Aarav.</h3><div className="lp-phone-workout"><span>TODAY’S PLAN</span><h4>Full-body<br/>foundations.</h4><small>25 min · At home</small><button onClick={onEnter}>Explore workout →</button></div><div className="lp-phone-progress"><div><b>3<span>/4</span></b><small>Sample weekly workouts</small></div><span className="lp-mini-ring"/></div><div className="lp-phone-coach"><span>RC</span><div><b>Your weekly check-in</b><small>A little support. A clear next step.</small></div></div></div><span className="lp-stage-caption">YOUR PLAN. YOUR PEOPLE. YOUR PROGRESS.</span></div></section>
 <section className="lp-team-section"><div className="lp-section"><div className="lp-section-head"><div><p className="lp-kicker">THE PEOPLE BEHIND YOUR PLAN</p><h2>Human support.<br/><em>From the very beginning.</em></h2></div><p>Our proposed pilot team brings training coordination and psychologist onboarding into one considered journey.</p></div><div className="lp-team-grid"><article><span className="lp-person-monogram">AK</span><div><p className="lp-kicker">TRAINER COORDINATION</p><h3>Akif</h3><p>Your point of contact for trainer coordination and a consistent weekly follow-up routine.</p></div><span className="lp-team-arrow">↗</span></article><article><span className="lp-person-monogram">TH</span><div><p className="lp-kicker">PSYCHOLOGIST ONBOARDING</p><h3>Thasleema</h3><p>An initial conversation to understand your needs and agree the guidance your trainer receives.</p></div><span className="lp-team-arrow">↗</span></article></div><p className="lp-team-note">Proposed pilot team. Availability and appointments are to be confirmed before enrolment.</p></div></section>
 <section className="lp-section lp-pricing" id="programme"><div><p className="lp-kicker">THE FOUNDING PILOT</p><h2>30 days.<br/>A stronger<br/><em>starting point.</em></h2><p>A small, online pilot for 10 adults in India. Personal attention, a manageable plan and a weekly conversation to keep you moving.</p><span className="lp-date">PLANNED SERVICE START · 15 OCTOBER 2026</span></div><div className="lp-price-card"><div className="lp-price-top"><span>YOUR 30-DAY PROGRAMME</span><span>FOUNDING COHORT</span></div><div className="lp-price"><sup>AED</sup>250<span>/ 30 days</span></div><p>Personal support from the first conversation.</p><ul><li>Psychologist onboarding session</li><li>A personalised trainer-led workout plan</li><li>Weekly trainer follow-ups</li><li>A space to follow your plan and progress</li></ul><button className="lp-primary" onClick={start}>Explore the pilot <span>↗</span></button><p className="lp-payment-note">Manual payment, verified by the team. India collection currency and payment method will be confirmed before enrolment.</p></div></section>
 <section className="lp-section lp-faq" id="questions"><div><p className="lp-kicker">LET’S CLEAR A FEW THINGS UP</p><h2>Good questions.<br/><em>Straight answers.</em></h2></div><div>{[['Who is the pilot for?','The first pilot is for adults aged 18 and over in India, with online coaching and an initial cohort of 10 clients.'],['Do I need a gym membership?','The proposed programme can be planned around training at home or at a gym. Your trainer will discuss your available space and equipment before finalising your plan.'],['How does psychologist onboarding work?','The programme includes an initial session with the psychologist. You agree what practical guidance may be shared with the trainer. Private counselling notes should stay separate from general training records.'],['Is nutrition coaching included?','Nutrition support and professional responsibility are still being defined. A nutritionist and personalised meal plans are not confirmed inclusions.'],['How do payments work?','Payment is manual, through an external method to be agreed. The team verifies receipt before activating programme access. This demo does not collect money.'],['Can I sign up or log in today?','This is an interactive design demo. The goal quiz and member area use sample information only. Real enrolment, secure accounts and bookings will be enabled when the service is ready.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="lp-final"><p className="lp-kicker">YOUR NEXT CHAPTER STARTS WITH ONE STEP</p><h2>Make every<br/><em>rep count.</em></h2><button className="lp-primary lp-big" onClick={start}>Find your starting point <span>↗</span></button><p>Your goals. A human connection. A way forward.</p></section></main><footer className="lp-footer"><div>{brand}<p>Personal training. Thoughtful support.</p></div><div><a href="#approach">Our approach</a><a href="#programme">The programme</a><button onClick={onEnter}>Member demo ↗</button></div><div className="lp-footer-bottom"><span>© 2026 RepCount · India pilot</span><span>Design demo · No live enrolment or payments</span></div></footer>
 <dialog className="lp-quiz" ref={ref} onCancel={()=>setQuiz(false)} aria-labelledby="quiz-title"><div className="dialog-inner"><button className="close" aria-label="Close quiz" onClick={()=>setQuiz(false)}>×</button><p className="lp-kicker">YOUR STARTING POINT · DEMO</p><div className="lp-quiz-progress"><span style={{width:`${(step+1)*25}%`}}/></div><h2 id="quiz-title">{['What would you like to work on?','Where will you feel at home?','What feels manageable?','Your starting point, mapped out.'][step]}</h2>{step<3?<><p>{['Choose the goal that matters most to you.','A good plan starts with the space you have.','This is a preference, not a prescribed workout schedule.'][step]}</p><div className="lp-options">{(step===0?['Build strength','Build a consistent routine','Feel more confident exercising']:step===1?['At home','At a gym','A mix of both']:['2 days','3 days','4 days']).map(v=><button key={v} className={(step===0?goal:step===1?place:days)===v?'chosen':''} aria-pressed={(step===0?goal:step===1?place:days)===v} onClick={()=>step===0?setGoal(v):step===1?setPlace(v):setDays(v)}>{v}<span>{(step===0?goal:step===1?place:days)===v?'✓':'○'}</span></button>)}</div><div className="lp-quiz-buttons">{step>0&&<button className="lp-back" onClick={()=>setStep(step-1)}>← Back</button>}<button className="lp-primary" onClick={()=>setStep(step+1)}>Continue →</button></div></>:<><div className="lp-quiz-result"><p><span>YOUR GOAL</span><b>{goal}</b></p><p><span>YOUR SETTING</span><b>{place}</b></p><p><span>YOUR PREFERENCE</span><b>{days} per week</b></p></div><p>Your next real step would be an onboarding conversation, followed by a trainer-approved plan. This preview has not submitted an application or matched you to a coach.</p><button className="lp-primary" onClick={()=>{setQuiz(false);onEnter();}}>Explore the sample member experience ↗</button><button className="lp-back" onClick={()=>setStep(0)}>Start again</button></>}<small>Demo only · No personal or health information collected.</small></div></dialog></div>;
}
