"use client";
import {useEffect,useRef,useState} from 'react';
const clips={workout:{src:'https://assets.mixkit.co/videos/52082/52082-720.mp4',poster:'https://assets.mixkit.co/videos/52082/52082-thumb-720-0.jpg'},review:{src:'https://assets.mixkit.co/active_storage/video_items/100544/1725385028/100544-video-720.mp4',poster:'https://assets.mixkit.co/active_storage/video_items/100544/1725385028/100544-video-thumb-720-0.jpg'}};
function clock(s:number){return `${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;}
export function ExerciseVideo({variant='workout'}:{variant?:'workout'|'review'}){
 const video=useRef<HTMLVideoElement>(null);const box=useRef<HTMLDivElement>(null);const manualPause=useRef(false);const [playing,setPlaying]=useState(false);const [time,setTime]=useState(0);const [duration,setDuration]=useState(0);const [error,setError]=useState(false);
 useEffect(()=>{const el=video.current;const wrap=box.current;if(!el||!wrap)return;let visible=false;const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
 const sync=()=>{if(visible&&!document.hidden&&!motion.matches&&!manualPause.current)void el.play().catch(()=>setPlaying(false));else el.pause();};
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;sync();},{threshold:.25});observer.observe(wrap);document.addEventListener('visibilitychange',sync);motion.addEventListener('change',sync);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',sync);motion.removeEventListener('change',sync);el.pause();};},[]);
 async function toggle(){const el=video.current;if(!el)return;if(el.paused){manualPause.current=false;try{await el.play();}catch{setError(true);}}else{manualPause.current=true;el.pause();}}
 return <div ref={box} className={'motion-video '+variant} data-video-demo={variant}><video ref={video} src={clips[variant].src} poster={clips[variant].poster} muted playsInline loop preload="metadata" aria-label={variant==='workout'?'Illustrative dumbbell squat exercise video':'Illustrative bench press review video'} onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>setError(true)}/><div className="motion-video-top"><span><i/>{variant==='workout'?'EXERCISE PREVIEW':'REVIEW EXAMPLE'}</span><button onClick={toggle} aria-label={playing?'Pause exercise video':'Play exercise video'}>{playing?'Ⅱ':'▶'}</button></div>{variant==='review'&&<div className="review-guidance"><span>RC</span><div><small>SAMPLE COACHING NOTE</small><p>Review your setup and movement with your trainer.</p></div></div>}{error?<div className="video-error">Video unavailable. Please reload to retry.</div>:<div className="motion-video-bottom"><div className="video-caption">{variant==='workout'?'Dumbbell squat':'Bench press · sample review'}</div><label className="video-scrub"><span className="sr-only">Seek exercise video</span><input aria-label="Seek exercise video" type="range" min="0" max={duration||1} step=".1" value={Math.min(time,duration||1)} onChange={e=>{if(video.current)video.current.currentTime=Number(e.target.value);}}/></label><div className="video-timestamp"><span>{clock(time)} / {clock(duration)}</span><span>Sound off · Stock demonstration</span></div></div>}</div>;
}
export default function MotionPhone(){const [sets,setSets]=useState(0);const [tab,setTab]=useState<'session'|'stats'>('session');const [period,setPeriod]=useState<'Week'|'Month'>('Week');const stats=period==='Week'?[20,30,0,25,0,30,0]:[85,110,95,125];const total=stats.reduce((a,b)=>a+b,0);
return <div className="product-phone motion-phone"><div className="device-island"/><div className="device-status"><b>9:41</b><span>▂▄▆ ▰</span></div><div className="motion-brand"><span><b>R</b>epCount</span><small>INTERACTIVE DEMO</small></div><div className="motion-phone-tabs" role="group" aria-label="Session or statistics"><button aria-pressed={tab==='session'} className={tab==='session'?'active':''} onClick={()=>setTab('session')}>Your session</button><button aria-pressed={tab==='stats'} className={tab==='stats'?'active':''} onClick={()=>setTab('stats')}>Your statistics ↗</button></div>
{tab==='session'?<><div className="motion-session-heading"><div><small>TODAY’S FOCUS</small><h3>Strength in motion.</h3></div><span>01 / 05</span></div><ExerciseVideo/><div className="motion-metrics"><div><small>SETS DONE</small><b>{sets}<em>/3</em></b></div><div><small>REPS / SET</small><b>8<em>target</em></b></div><div><small>REST</small><b>60<em>sec</em></b></div></div><button className="motion-complete" onClick={()=>setSets(sets===3?0:sets+1)}>{sets===3?'Reset sample session ↻':'Complete sample set'}<span>{sets===3?'✓':`${sets+1} / 3 →`}</span></button><div className="motion-set-dots">{[0,1,2].map(i=><span key={i} className={i<sets?'done':''}>{i<sets?'✓':i+1}</span>)}<small>Sample programme · No automatic rep detection</small></div></>:<><div className="motion-session-heading"><div><small>CONSISTENCY, MADE VISIBLE</small><h3>Your work adds up.</h3></div></div><div className="motion-period" role="group" aria-label="Sample statistics period">{(['Week','Month'] as const).map(p=><button aria-pressed={period===p} key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div><div className="motion-stat-total"><b>{total}<span>min</span></b><small>Sample training time · this {period.toLowerCase()}</small></div><div className="motion-chart" key={period} role="img" aria-label={`${period} sample training minutes: ${stats.join(', ')}`}>
{stats.map((v,i)=><div key={i}><span>{v||'—'}</span><i style={{height:`${v/Math.max(...stats)*120+3}px`}}/><small>{period==='Week'?['M','T','W','T','F','S','S'][i]:`W${i+1}`}</small></div>)}</div><div className="motion-stat-cards"><div><span>SESSIONS</span><b>{period==='Week'?'4':'16'}</b><small>Sample activity</small></div><div><span>COMPLETION</span><b>80<em>%</em></b><small>{period==='Week'?'4 of 5 planned':'16 of 20 planned'}</small></div></div><div className="motion-week-goal"><div><b>One step at a time.</b><span>80%</span></div><div className="motion-goal-track"><i/></div><p>Illustrative records, not measured health or wearable data.</p></div><button className="motion-complete" onClick={()=>setTab('session')}>Back to your session <span>→</span></button></>}
<div className="motion-bottom"><span className="active">◫<small>Today</small></span><span>◷<small>Plan</small></span><span>↗<small>Progress</small></span><span>◎<small>Coach</small></span></div><div className="device-home"/></div>;
}
